# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('friendemail', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('bio', models.CharField(blank=True, default='', max_length=255)),
                ('motto', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
